spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BankApp
    username: root
    password: oyeks123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update
  mail:
    host: smtp.gmail.com
    port: 465
    username: {YOUR EMAIL}
    password: {YOUR APP PASSWORD FROM GMAIL}
    properties:
      mail:
        smtp:
          auth: true
          #          starttls:
          #            enable: true
          ssl:
            enable: true
